### ISSUE TITLE
potni nalogi - izpis

### ISSUE THREAD

**Issue by SpelaOman** [bubi-luka/BubiRacun#160]
Pri tisku potnega naloga določene vrstice izpiše eno čez drugo, tako da se nič ne vidi. Dva različna primera, v katerih vrsticah se to pojavlja (ampak ne pri vseh potnih nalogih) sem ti dala na mizo.

**Comment by SpelaOman** [comment]
Izpis vrstic se ne prekriva več, je videti vse ok.

**Comment by SpelaOman** [comment]
Ne izpiše še kraja Kranj pri vrstici:
Stanujoč:
Prebivališče:

**Comment by bubi-luka** [comment]
Zapiram, čeprav #162 ne bo izpolnjena.
