### ISSUE TITLE
Prazna tabela - ni vrstic

### ISSUE THREAD

**Issue by bubi-luka** [bubi-luka/BubiRacun#162]
V primeru, da tabela ni izpolnejna, ne upošteva višine vrstic, čeprav je tam besedilo (odhod:, vrnitev:, ob:, ob:, ...). Enako ne upošteva višine vrstic polj pri prejemniku potnega naloga, če tam ni besedila (trenutno je problematičen naziv).

Predlog rešitve:
V kolikor je polje nosilec oblike potnega naloga, mora obstajati tudi, če tam ni besedila. Višina vrstice se gleda glede na višino prebranega besedila, dolžina pa glede na dolžino besedila iz baze podatkov.
V kolikor besedilo ni potrebno, potem se gleda, ali je besedilo prisotno in se v primeru, da ni, tudi ne zapiše niti prebrano besedilo.

**Comment by SpelaOman** [comment]
Prilagam trenutno stanje... ![prazna_tabela_vrstice](https://cloud.githubusercontent.com/assets/1206206/5602177/0c709506-933c-11e4-8eb5-ccafb4466c3a.jpg)

**Comment by bubi-luka** [comment]
Preveč dela, ne bom izpeljal. Če se pojavi potreba na specifičnem polju, bom to naredil samo za tisto polje.

Smiselno bi bilo edino v primeru, da bi popolnoma prenovil pristop k tiskanju z uporabo novih razredov in bi bilo vzdrževanje kode lažje in bolj smiselno. Treba bi bilo pregledati, kje je velikost vrstice večja, ali pri fiksnem besedilu ali pri variabilnem delu besedila ter kaj narediti, če je besedilo prazno.
