### ISSUE TITLE
Logotip naj bo shranjen v bazi

### ISSUE THREAD

**Issue by bubi-luka** [bubi-luka/BubiRacun#170]
Logotip vsakega računa je vezan na pot do logotipa, ki pa se ob novih namestitvah programa izgubi (drugo up. ime, druga pot shranjevanja podatkov, ...). Pri tem se izgubi tudi povezava med računom in logotipom, kar pomeni, da je treba ročno popraviti vsak dokument za nazaj.

Predlagam shranjevanje logotipov v bazi ali kakem ekvivalentnem formatu, ki bi ob prenosu programa se prenesel skupaj z ostalimi podatki.

**Comment by SpelaOman** [comment]
#173
